### ISSUE TITLE
Implement NetworkPolicy

### ISSUE THREAD

**Issue by terinjokes** [sourcegraph/deploy-sourcegraph#213]
In our Kubernetes cluster, we're heavy users of [Network Policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/) for both Pod ingress and egress. We'd like to continue this for Sourcegraph, but currently there's none provided as a base.

I can probably brute force Network Policies from error messages, but it might be easier and faster for someone more familiar with the dependencies to properly setup.

**Comment by beyang** [comment]
@terinjokes a couple of clarifying questions:
* Is the goal here to enforce a policy on overall ingress/egress traffic between Sourcegraph and the outside world or to enforce a policy on traffic between pods in the Sourcegraph cluster itself?
* If the latter, is the need for a Network Policy due to Sourcegraph being deployed into a cluster that also has non-Sourcegraph pods or just due to a general policy (e.g., "all Kubernetes clusters must have NetworkPolicies that constrain internal network traffic to only what's minimally necessary")
* If due to a general policy, what are the requirements that the set of Network Policies needs to meet. Is there an internal definition you can share?

**Comment by terinjokes** [comment]
1. Ideally a policy for both traffic between the pods and the outside word, and pods and other Sourcegraph pods. However, a blanket policy (pods within the namespace are allowed to communicate with other pods in the namespace) might work for the latter, if you don't want to denote the specifics.
2. It's a general policy for us that all deployments have network policies. This is enforced with a network policy that drops all traffic by default.
3. We don't have a formal definition right now. The assumption is be reasonable. (Eg: don't simply define a network policy for 0.0.0.0/0)
4. It's not extremely urgent. I can make my guesses to some policies.

**Comment by beyang** [comment]
Got it, thanks. I'm going to put this down as a stretch goal for 3.3 (current milestone): https://github.com/sourcegraph/sourcegraph/issues/2809. If you decide you'd like to explore this more on your own before we get to it, let me know and I can sketch out the network topology of the different services.

**Comment by beyang** [comment]
Migrating issue to https://github.com/sourcegraph/sourcegraph/issues/9726, so this no longer falls through the cracks.
