### ISSUE TITLE
Clarify recommended configurations

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/deploy-sourcegraph#84]
It is kind of expected that customers at least read through all the configurations listed in "common configurations". Maybe we should rename this to "recommended configurations"?

See discussion here:
https://github.com/sourcegraph/deploy-sourcegraph/commit/faacd647d13d72f3576155ea368e88cb0f8f8fa6#r30388357

cc @beyang

**Comment by beyang** [comment]
People will not be guaranteed to read through anything unless it's placed on the main install path. There are a couple issues here:
* The "common configurations" list includes configurations that are not required: https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/configure.md#common-configuration. That means that the storage class requirement will be interpreted as "optional".
* It is necessary to re-provision the volume when switching the storage class from the default to the one specifying SSDs. That means *immediately* after spinning up a Sourcegraph cluster, a user will have to blow away the original persistent volume (which may even require manual `kubectl` commands since the previous volume is already bound to the PVC).

If our intent (and I think it should be) is to have 99% of Data Center users use SSDs for their persistent volumes, we should just include it in the main install instructions here: https://github.com/sourcegraph/deploy-sourcegraph/blob/master/docs/install.md.
